title: A Blog
description: "A blog. Specifically, Josh Cannon's Blog."
rss-description: "A blog. Specifically, Josh Cannon's Blog."
url: "https://joshcannon.me"

author: Josh Cannon
navbar-col: "#FDA"
footer-col: "#FDA"
hover-col: "#E2725B"
footer-hover-col: "#E2725B"
link-col: "#9A6B32"
footer-link-col: "#CFB288"

site-css: assets/css/site.css

navbar-links:
  Now: "now"

social-network-links:
  email: "joshdcannon@gmail.com"
  rss: true
  github: thejcannon
  mastodon: fosstodon.org/@thejcannon

remote_theme: daattali/beautiful-jekyll@6.0.1
plugins:
  - jekyll-feed

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      head-extra: post_head_extra.html
      before-content: post_layout.html
